Making the certificate manager ordering optional, as well as adding Edge Certificate ordering to IKS
IBM/cis-integration pull request #30
Opened 2021-08-04 15:52 UTC by Pseusco

Since we need to order an Edge Certificate for IKS as well as Code Engine, I moved certcreate.py and delete_certs.py to the common folder.

iks.py now orders an edge certificate and can delete it with the delete option.

iks.py now also asks the user if they want to create a new secret before ordering a TLS certificate in the certificate manager.

2021-08-04 16:09 UTC, Chris-Springstead requested changes

2021-08-04 16:09 UTC, Chris-Springstead commented on src/iks/iks.py
> +        print("Can order a new TLS Certificate and import as a secret to IKS or use the default secret already in IKS")
Maybe a clearer message here saying we're currently using the default IKS secret but if they wish we can order a new TLS certificate and import that for the secret.

2021-08-04 16:58 UTC, Chris-Springstead submitted a review, later dismissed

2021-08-04 20:21 UTC, Pseusco commented
I added more to the terraform implementation. The ingress creation was also not working before and I attempted to fix it.

2021-08-04 21:51 UTC, akulio4668 requested changes
I think we also need to include the new variables (`ingress` and `cert_name`) in both the `variables.tf` file in the `root_terraform` directory as well as the IKS module initialization in the `main.tf` file in `root_terraform` just to ensure that they are part of the overall module structure of the Terraform created by our project.

2021-08-04 21:55 UTC, akulio4668 commented
I think the variable stuff in `root_terraform` is almost there; we might just need default values for all of the variables that don't currently have them though, cause if we try to make a `ce` module for instance, the workspace will error out and say that `cluster_id`, `ingress`, and `cert_name` don't have assigned values.

2021-08-05 15:20 UTC, akulio4668 approved these changes, later dismissed

2021-08-05 16:11 UTC, Chris-Springstead submitted a review, later dismissed

2021-08-05 16:13 UTC, Chris-Springstead commented
Looks good. Maybe wait until we merge the testing branch into master before we merge this one since I think this has the latest updates to iks.py.

2021-08-09 19:45 UTC, Pseusco commented
Been changing a bunch of the stuff in the terraform. Creating a secret in iks after ordering a certificate in the certificate manager was not working and I tried to fix it. Not 100% sure it's working because I got rate-limited in both CIS instances

2021-08-12 15:50 UTC, Chris-Springstead approved these changes

2021-08-12 19:43 UTC, akuljos approved these changes

2021-08-12 19:57 UTC, merged