Delete ingress
IBM/cis-integration pull request #33
Opened 2021-08-06 13:48 UTC by dpeace8

Created function to delete ingress file

2021-08-06 17:01 UTC, akulio4668 approved these changes, later dismissed

2021-08-09 19:40 UTC, Pseusco requested changes
There are a couple commented-out sections in iks.py that look like they were only commented out for testing, so they should probably be uncommented. Eventually we will need to update the README to represent the new argument for the delete function, but that doesn't necessarily need to be done now.

2021-08-09 19:40 UTC, Pseusco commented on src/iks/iks.py
> +        '''
We shouldn't comment out the DNS record deletion. Our delete function should still be able to delete the DNS records

2021-08-11 17:45 UTC, Pseusco approved these changes

2021-08-11 20:50 UTC, akulio4668 approved these changes

2021-08-11 20:51 UTC, merged