Modified tests to fit new dns file
IBM/cis-integration pull request #35
Opened 2021-08-12 13:25 UTC by michaelhilborn

2021-08-12 14:52 UTC, akulio4668 requested changes
This is my fault because I forgot to take it out but can you remove the TO DO comment here: [test_dns_creator.py:220-223](https://github.com/IBM/cis-integration/blob/ef2b085fcbfb6f7b4565cb0518621f1ef756f5ad/tests/test_dns_creator.py#L220-L223)

2021-08-12 15:51 UTC, Chris-Springstead approved these changes, later dismissed

2021-08-12 19:44 UTC, akulio4668 approved these changes

2021-08-13 13:57 UTC, Chris-Springstead approved these changes

2021-08-13 13:58 UTC, merged